/* One-shot helper to self-host the Google Fonts used by the site.
   Parses the Google CSS (with woff2 URLs), keeps latin + latin-ext only,
   downloads each .woff2 to assets/fonts/ with a stable name, and writes a
   replacement local-fonts.css that the site can import instead of the
   Google CDN <link>. Run with `node scripts/fetch-fonts.mjs`. */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const FONTS_DIR = resolve(ROOT, 'assets/fonts');
const OUT_CSS  = resolve(ROOT, 'assets/fonts/local-fonts.css');
const SRC_CSS  = resolve(__dirname, '.gfonts.tmp.css'); // pre-fetched

mkdirSync(FONTS_DIR, { recursive: true });

const css = readFileSync(SRC_CSS, 'utf8');

// Split the file into per-@font-face blocks; the leading subset comment
// (`/* latin */`) is kept with the block via lookbehind in the regex.
const blocks = css.split(/(?=\/\*\s*[a-z-]+\s*\*\/)/g).map(s => s.trim()).filter(Boolean);

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

let outCss = `/* Self-hosted Google Fonts subset (latin + latin-ext).
   Auto-generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n`;
let downloads = [];

for (const block of blocks) {
  const subsetMatch = block.match(/^\/\*\s*([a-z-]+)\s*\*\//);
  if (!subsetMatch) continue;
  const subset = subsetMatch[1];
  if (!KEEP_SUBSETS.has(subset)) continue;

  const fam = block.match(/font-family:\s*'([^']+)'/);
  const wgt = block.match(/font-weight:\s*(\d+)/);
  const url = block.match(/src:\s*url\(([^)]+)\)/);
  if (!fam || !wgt || !url) continue;

  const family = fam[1];
  const weight = wgt[1];
  const remoteUrl = url[1];
  const localName = `${slug(family)}-${weight}-${subset}.woff2`;
  const localPath = `${family}@${weight}@${subset}.woff2`; // unused
  const cssPath   = `assets/fonts/${localName}`;
  downloads.push({ remoteUrl, localFile: resolve(FONTS_DIR, localName) });

  outCss += block
    .replace(/src:\s*url\([^)]+\)\s*format\('woff2'\)/, `src: url(/${cssPath}) format('woff2')`)
    + '\n\n';
}

writeFileSync(OUT_CSS, outCss);
console.log(`wrote ${OUT_CSS}`);
console.log(`will download ${downloads.length} files`);

// Emit a curl manifest so the bash side can fetch in parallel
const manifest = downloads.map(d => `${d.remoteUrl} ${d.localFile}`).join('\n');
const manifestPath = resolve(__dirname, '.font-manifest.tmp.txt');
writeFileSync(manifestPath, manifest);
console.log(`manifest ${manifestPath}`);
